[project]
name = "python-ctrip"
version = "0.1.16"
description = "ctrip python sdk"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "asyncio>=4.0.0",
    "httpx>=0.28.1",
    "openpyxl>=3.1.5",
    "pandas>=2.3.2",
    "pydantic>=2.11.7",
    "python-dotenv>=1.1.1",
]
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

# 新增这个部分，用来配置 setuptools
[tool.setuptools]
package-dir = {"" = "src"}
packages = {find = {where = ["src"]}}
